---
- name: installing or uninstalling s/w packages
  hosts: all
  vars:
    - a: tomcat8
    - b: present
    - c: no

  tasks:
     - name: install/uninstall software package
       apt:
         name: "{{a}}"
         state: "{{b}}"
         update_cache: "{{c}}"

...
